<?php

/**
 * @file
 * Allows support of a new view handler.
 */


/**
 * Implements hook_theme().
 */
function jssor_theme() {
  return array(
    'jssor' => array(
      'variables' => array(
        'view' => NULL,
        'rows' => NULL,
      ),
      'file' => 'jssor.theme.inc',
    ),
  );
}


/**
 * Implements hook_views_pre_render().
 */
function jssor_views_pre_render($view) {
  if ($view->storage->id() === 'test') {
    //$view->element['#attached']['js'][] = array('type' => 'setting', 'data' => $settings);
    //$view->element['#attached']['library'][] = 'views/views.ajax';
  }

  return $view;
}

/**
 * Implements hook_library().
 */
function jssor_library() {
  // Get the external JSSOR Slider library path.
  $slider_lib_src = libraries_get_path('jssor-slider', true);
  // Get this module's base location.
  $base_path = drupal_get_path('module', 'jssor');
  // Add the JSSOR files as Drupal library.
  return array(
    'jquery.jssor.slider' => array(
      'title' => 'JSSOR Slider',
      'website' => 'http://www.jssor.com',
      'version' => '17.0',
      'js' => array(
        $base_path . '/js/jssor_views.js' => array(),
        $slider_lib_src . '/js/jssor.slider.min.js' => array(),
      ),
      'css' => array(
        $base_path . '/css/jssor-skin.css' => array(
          'type' => 'file',
          'media' => 'screen',
        ),
      ),
      'dependencies' => array(
        // Require jQuery UI core by System module.
        array('system', 'jquery'),
      ),
    ),
  );
}

function jssor_libraries_info() {
  return array(
    'jssor-slider' => array(
      'name' => 'JSSOR Slider',
      'vendor url' => 'http://www.jssor.com',
      'download url' => 'https://github.com/jssor/slider/archive/master.zip',
      // Optional: If, after extraction, the actual library files are contained in
      // 'sites/all/libraries/example/lib', specify the relative path here.
      'path' => 'js',
      // Specify arguments for the version callback. By default,
      'version arguments' => array(
        'file' => 'js/jssor.js',
        'pattern' => '@[Js]ssor\s+([0-9a-zA-Z\.-]+)@',
        'lines' => 5,
        'cols' => 50,
      ),
    ),
  );
}
